package rmi;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class connection extends javax.swing.JFrame {

    /** Creates new form connection */
    public connection() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        choix1 = new javax.swing.JLabel();
        choix2 = new javax.swing.JLabel();
        res1label = new javax.swing.JLabel();
        res2label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rb = new javax.swing.JRadioButton();
        pb = new javax.swing.JRadioButton();
        sb = new javax.swing.JRadioButton();
        result = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        choice22 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pierre-Papier-Ciseaux ");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pierre-Papier-Ciseaux ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTextField1.setText("127.0.0.1");

        jTextField2.setText("2011");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("ADRESSE IP");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("NUMERO DE PORT");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Montrer Le Résultat");
        jButton1.setPreferredSize(new java.awt.Dimension(140, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        choix1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choix1.setText("*");
        choix1.setPreferredSize(new java.awt.Dimension(100, 100));

        choix2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choix2.setText("*");
        choix2.setPreferredSize(new java.awt.Dimension(100, 100));

        res1label.setBackground(new java.awt.Color(255, 0, 0));
        res1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        res2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1000_F_502155530_9ywMCS4wqAoYIv6UKNGsNQEqpqfrdKLt - Copie - Copie.jpg"))); // NOI18N

        buttonGroup1.add(rb);

        buttonGroup1.add(pb);

        buttonGroup1.add(sb);

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText("Result ...");

        confirm.setBackground(new java.awt.Color(255, 51, 51));
        confirm.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirmer");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jTextField3.setText("1 OR 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(res1label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(141, 141, 141)
                                        .addComponent(res2label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(choix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(choix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(choice22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rb)
                                .addGap(116, 116, 116)
                                .addComponent(pb)
                                .addGap(118, 118, 118)
                                .addComponent(sb)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(confirm)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(60, 60, 60))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(res1label)
                    .addComponent(res2label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choice22, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb)
                    .addComponent(pb)
                    .addComponent(sb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        adrs = jTextField1.getText();
        prt = jTextField2.getText();
        number = jTextField3.getText();

        res1label.setText("" + score1);
        res2label.setText("" + score2);
        numb = Integer.parseInt(number);

        int port = Integer.parseInt(prt);

        if ((port > 1024)) {
            if (rb.isSelected() == true) {// rock
                choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.jpg")));
                valA = 1;
            }
            if (pb.isSelected() == true) {// paper
                choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.jpg")));
                valA = 2;
            }
            if (sb.isSelected() == true) {// sci
                choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.jpg")));
                valA = 3;
            }
            client ab = new client();
            try {
                if (numb == 1) {
                    choice = ab.exe_cli_choice1(numb, valA, "", adrs, prt);
                    System.out.println("le choix des joueur est :  " + choice);
                    choice2 = ab.exe_cli_choice12(numb, "", adrs, prt);
                    System.out.println("le choix des joueur 2 est :  " + choice2);
                } else if (numb == 2) {

                    choice = ab.exe_cli_choice2(numb, valA, "", adrs, prt);
                    System.out.println("le choix des joueur est :  " + choice);
                    choice2 = ab.exe_cli_choice22(numb, "", adrs, prt);
                    System.out.println("le choix des joueur 2 est :  " + choice2);
                }
                if (valA == 1) {

                    double choixx2 = 0;
                    double valeur = ab.exe_cli_game(numb, "", adrs, prt);

                    if (choice2 == 1) {
                        result.setText("Partie Nulle");
                        result.setForeground(Color.BLACK);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.jpg")));
                    } else if (choice2 == 2) {
                        result.setText("vous avez perdu :( ");
                        result.setForeground(Color.RED);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        score2++;
                        res2label.setText("" + score2);
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.jpg")));
                    } else if (choice2 == 3) {
                        result.setText("vous avez gagné *-* ");
                        score1++;
                        res1label.setText("" + score1);
                        result.setForeground(Color.GREEN);

                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.jpg")));
                    }
                     else if(choice2==0){
                        JOptionPane.showMessageDialog(new JFrame(), "le deuxième joueur n'as pas encore choisi ");
                    }
                }
                if (valA == 2) {// paper

                    if (choice2 == 1) {
                        result.setText("vous avez gagné *-* ");
                        result.setForeground(Color.GREEN);
                        score1++;
                        res1label.setText("" + score1);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.jpg")));
                    } else if (choice2 == 2) {
                        result.setText("Partie Nulle");
                        result.setForeground(Color.BLACK);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.jpg")));
                    } else if (choice2 == 3) {
                        result.setText("vous avez perdu :( ");
                        result.setForeground(Color.RED);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.jpg")));
                        score2++;
                        res2label.setText("" + score2);
                    }
                     else if(choice2==0){
                        JOptionPane.showMessageDialog(new JFrame(), "le deuxième joueur n'as pas encore choisi ");
                    }
                }
                else if(valA==0){
                     if(choice2!=0)
                     {
                        JOptionPane.showMessageDialog(new JFrame(), "vous n'avez pas encore choisi ");}
                     else{
                      JOptionPane.showMessageDialog(new JFrame(), "les joueurs n'ont pas encore choisi");
                     }
                    
                }
                    
               else if (valA == 3) {// sci

                    if (choice2 == 1) {
                        result.setText("vous avez perdu :( ");
                        result.setForeground(Color.RED);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        score2++;
                        res2label.setText("" + score2);
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.jpg")));
                    } else if (choice2 == 2) {
                        result.setText("vous avez gagné *-* ");
                        score1++;
                        res1label.setText("" + score1);
                        result.setForeground(Color.GREEN);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.jpg")));
                    } else if (choice2 == 3) {
                        result.setText("Partie Nulle");
                        result.setForeground(Color.BLACK);
                        result.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
                        choix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.jpg")));
                    }
                     else if(choice2==0){
                        JOptionPane.showMessageDialog(new JFrame(), "le deuxième joueur n'as pas encore choisi ");
                    }


                    if (numb == 1) {
                        choice = ab.exe_cli_choice1(numb, valA, "", adrs, prt);
                        System.out.println("le choix des joueur est :  " + choice);
                        choice2 = ab.exe_cli_choice12(numb, "", adrs, prt);
                        System.out.println("le choix des joueur 2 est :  " + choice2);
                    } else if (numb == 2) {

                        choice = ab.exe_cli_choice2(numb, valA, "", adrs, prt);
                        System.out.println("le choix des joueur est :  " + choice);
                        choice2 = ab.exe_cli_choice22(numb, "", adrs, prt);
                        System.out.println("le choix des joueur 2 est :  " + choice2);
                    }
                    
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(),
                        "IL Y A UNE ERREUR OU BIEN LE SERVEUR N'EST PAS CONNECTER ");
                Logger.getLogger(connection.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "LE NUMERO DE PORT DOIT ETRE SUPERIEUR A 1024");
            connection a = new connection();
            a.setVisible(true);
        }

    }// GEN-LAST:event_jButton1ActionPerformed
    

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmActionPerformed

        adrs = jTextField1.getText();
        prt = jTextField2.getText();

        res1label.setText("" + score1);
        res2label.setText("" + score2);

        int port = Integer.parseInt(prt);

        if (rb.isSelected() == true) {// rock
            choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.jpg")));
            valA = 1;
        }
        if (pb.isSelected() == true) {// paper
            choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.jpg")));
            valA = 2;
        }
        if (sb.isSelected() == true) {// sci
            choix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.jpg")));
            valA = 3;
        }

        if ((port > 1024)) {
            client ab = new client();

            try {
                if (numb == 1) {
                    choice = ab.exe_cli_choice1(numb, valA, "", adrs, prt);
                    System.out.println("le choix des joueur est :  " + choice);
                    choice2 = ab.exe_cli_choice12(numb, "", adrs, prt);
                    System.out.println("le choix des joueur 2 est :  " + choice2);
                } else if (numb == 2) {

                    choice = ab.exe_cli_choice2(numb, valA, "", adrs, prt);
                    System.out.println("le choix des joueur est :  " + choice);
                    choice2 = ab.exe_cli_choice22(numb, "", adrs, prt);
                    System.out.println("le choix des joueur 2 est :  " + choice2);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(),
                        "IL Y A UNE ERREUR OU BIEN LE SERVEUR N'EST PAS CONNECTER ");
                Logger.getLogger(connection.class.getName()).log(Level.SEVERE, null, e);
            }
        } // GEN-LAST:event_confirmActionPerformed
        if (score1 > 4) {
            if (choice2 == 1) {
                choice22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rock.b&w.jpg")));
               
            } else if (choice2 == 2) {
                choice22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paper.b&w.jpg")));
               
            } else if (choice2 == 3) {
                choice22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sci.b&w.jpg")));
                
            }
        }
        else
        { JOptionPane.showMessageDialog(new JFrame(),"pour voir le choix du second joueur vous devez avoir +5score"+"\n (vous pouvez modifier votre choix aussi ^-^)");
               } 

    }
    

    static public double valA;
    static double choice2;
    static double choice;
    static int score1 = 0;
    static int score2 = 0;
    public static String adrs;
    public static String prt;
    public static String number;
    public static double numb;

    public static int taille;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new connection().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel choice22;
    private javax.swing.JLabel choix1;
    private javax.swing.JLabel choix2;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton pb;
    private javax.swing.JRadioButton rb;
    private javax.swing.JLabel res1label;
    private javax.swing.JLabel res2label;
    private javax.swing.JLabel result;
    private javax.swing.JRadioButton sb;
    // End of variables declaration//GEN-END:variables
}
